User.create!(name: '斎藤', age: 30, address: '静岡')
User.create!(name: '田中', age: 28, address: '東京')
User.create!(name: '佐藤', age: 24, address: '大阪')
User.create!(name: '鈴木', age: 15, address: '高知')
User.create!(name: '高橋', age: 56, address: '岐阜')
User.create!(name: '加藤', age: 45, address: '三重')
